### ISSUE TITLE
Hacktoberfest 2022: Localizations wanted

### ISSUE THREAD

**Issue by leekelleher** [leekelleher/umbraco-contentment#261]
Help to localize the English language labels into other languages.

Currently, some of the UI labels are in the English language file:
<https://github.com/leekelleher/umbraco-contentment/blob/develop/src/Umbraco.Community.Contentment/Web/UI/App_Plugins/Contentment/Lang/en.xml>

_(I am aware that there are many other UI labels that are hardcoded throughout the codebase! 😬)_

As a start, if you have the skills to translate the existing English language labels into another language, that would be greatly appreciated.

So far we have Danish and Portuguese (Brazil) done.
<https://github.com/leekelleher/umbraco-contentment/tree/develop/src/Umbraco.Community.Contentment/Web/UI/App_Plugins/Contentment/Lang>

---

### Achieved during Hacktoberfest

- [x] #268 Spanish, ¡Muchos gracias! @Happy-reindeer007
- [x] #269 Swedish, Tack så mycket! @enkelmedia
- [x] #270 Dutch, Heel erg bedankt! @erikjanwestendorp
- [x] #271 French, Très bien merci! @mikecp
- [x] #277 Portuguese updates, Muito obrigado! @leocb

Thanks for the great efforts so far! 🎉

**Comment by Happy-reindeer007** [comment]
Hi there! I'm interested in working on this issue. I can help with Spanish translation ;-)

**Comment by leekelleher** [comment]
@Happy-reindeer007 Muchos gracias! 😀 That'd be excellent.

**Comment by leekelleher** [comment]
Closing this ticket off, as it was created for the duration of Hacktoberfest 2022.

I'm very happy with the localization submissions, thank you to all involved! 👏👏👏
